services:
  mongo:
    image: mongo:6.0.13
    ports:
      - "27017:27017"
  server:
    build:
      context: .
    environment:
        - NODE_ENV=production
    container_name: blog
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on: [ mongo ]

